### ISSUE TITLE
MediaQuery breakpoints issue

### ISSUE THREAD

**Issue by teland94** [EdCharbeneau/BlazorSize#44]
When I load the application on mobile, I see the switching from Unmatched view to Matched up to one second. Is this a rendering performance issue? The sample code is below.
```
<MediaQuery Media="@Breakpoints.SmallDown">
    <Matched>
        <WeatherCards Data="forecasts"></WeatherCards>
    </Matched>
    <Unmatched>
        <WeatherGrid Data="forecasts"></WeatherGrid>
    </Unmatched>
</MediaQuery>
```

**Comment by EdCharbeneau** [comment]
This is due to the JavaScript interop and applications having an unknown state while the Interop is unavailable.

```razor
<MediaQuery Media="@Breakpoints.SmallDown">
    <Matched>
        <WeatherCards Data="forecasts"></WeatherCards>
    </Matched>
    <Unmatched>
        <WeatherGrid Data="forecasts"></WeatherGrid>
    </Unmatched>
</MediaQuery>
```

Blazor life cycle methods are as follows https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0

1. Create the component's instance.
2. Perform property injection. Run SetParametersAsync.
3. Call OnInitialized{Async}. If a Task is returned, the Task is awaited and the component is rendered. If a Task isn't returned, the component is rendered.
4. JavaScript is available, MediaQuery is tested
5. component is re-rendered

Since JavaScript is only available after rendering has happened (4), then it is impossible to render the correct media query response on the first rendering pass. See issue: https://github.com/EdCharbeneau/BlazorSize/issues/35

In order to mask the switch between small/large you must use a loading flag and hide all content within the MediaQuery until rendering is complete and then show the content.

**Comment by EdCharbeneau** [comment]
Thanks for adding the issue. I created a KB article to detail why it happens and how to fix it.

I'm going to leave this issue open for voting for the Template to not show by default until loading is complete. This will be for Code Free Templates only and not for `@bind-Matched`. I still believe Blazor developers should add proper loading workflows to their pages, but the Template was intended to be "code free solution".

**Comment by teland94** [comment]
IsLoading = false in OnAfterRender hook didn't solve the issue.
